{{ if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- range .Values.grafana.dashboardsConfigMaps }}
  name : {{ .configMapName|quote }}
  {{- end}}
  labels:
    app: {{ template "gateway.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ if .Values.grafana.files.enabled }}
  gateway-service-metrics.json: {{ .Files.Get .Values.grafana.files.serviceMetricJSONPath | toJson }}
  {{ end }}
{{ end }}
