helm-extra-args: --timeout 600s --dry-run
check-version-increment: true
validate_maintainers: false
debug: true
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - influx=https://helm.influxdata.com/
  - stable=https://kubernetes-charts.storage.googleapis.com
  - hazelcast=https://hazelcast-charts.s3.amazonaws.com/
