apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" .}}-license
  annotations:
    description: Template for Secrets for the Gateway license
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  license: {{ .Values.license.value | b64enc | quote }}