apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" .}}-license
  annotations:
    description: Template for Secrets for the Gateway license
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  license: {{ .Values.license.value | b64enc | quote }}

# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ template "gateway.fullname" .}}-certs
#   labels:
#     name: {{ template "gateway.fullname" .}}-certs
#   annotations:
#     description: This is a packaged private key pair that we ship with for testing purposes, if you'd like to replace this then make sure you update the sts gateway too.
# type: Opaque
# data:
#   ssl.p12: {{ .Files.Get "files/ssl.p12" | b64enc | quote }}